export const LIST_FRAME_SIDE_WIDTH_PX = 14
export const LIST_FOUNDATION_WIDTH_PX = 2
export const LIST_FRAME_BODY_WIDTH_PX =
	LIST_FRAME_SIDE_WIDTH_PX * 2 + LIST_FOUNDATION_WIDTH_PX
export const LIST_FRAME_GAP_PX = 8
export const LIST_SLOT_WIDTH_PX = LIST_FRAME_BODY_WIDTH_PX + LIST_FRAME_GAP_PX
export const LIST_SECTION_PADDING_X_PX = 14

export const VISUAL_FRAME_SIDE_WIDTH_PX = 64
export const VISUAL_FRAME_SIDE_GAP_PX = 4
export const VISUAL_FRAME_TOTAL_WIDTH_PX =
	VISUAL_FRAME_SIDE_WIDTH_PX * 2 + VISUAL_FRAME_SIDE_GAP_PX
export const VISUAL_SECTION_PADDING_X_PX = 5

export const INDICATOR_WIDTH_PX = 4
