GRATHEON COMMERCIAL LICENSE AGREEMENT

Copyright (c) 2025 Gratheon (Artjom Kurapov)

This Commercial License Agreement ("Agreement") is entered into between
Gratheon ("Licensor") and the customer identified in the Order Form
("Licensee").

WHEREAS, Licensor has developed and owns proprietary software for beehive
management and analytics (the "Software"); and

WHEREAS, Licensee wishes to obtain a commercial license to use the Software
under terms different from the GNU Affero General Public License v3.

NOW, THEREFORE, in consideration of the mutual covenants and agreements
herein contained, the parties agree as follows:

1. DEFINITIONS

   1.1 "Software" means the Gratheon beehive management platform, including
       all components, modules, and services as specified in the Order Form.

   1.2 "Commercial Use" means use of the Software for commercial purposes,
       including but not limited to revenue-generating activities.

   1.3 "Order Form" means the document specifying the licensed components,
       number of users, hives, deployment type, fees, and term.

2. GRANT OF LICENSE

   2.1 Subject to the terms of this Agreement and payment of applicable fees,
       Licensor grants Licensee a non-exclusive, non-transferable license to:

       (a) Use, execute, and display the Software
       (b) Modify the Software for internal use
       (c) Deploy the Software on Licensee's infrastructure (on-premise
           license) or use hosted version (SaaS license)
       (d) Use the Software for Commercial Use

   2.2 This license explicitly exempts Licensee from the requirements of the
       GNU Affero General Public License v3, including:

       (a) No obligation to disclose source code
       (b) No obligation to license modifications under AGPL
       (c) No copyleft obligations to downstream users

3. RESTRICTIONS

   3.1 Licensee shall NOT:

       (a) Redistribute, resell, or sublicense the Software as a standalone
           product
       (b) Use the Software to provide competing beehive management SaaS
           services to third parties
       (c) Remove or modify any proprietary notices, labels, or marks
       (d) Reverse engineer, decompile, or disassemble the Software (except
           as permitted by law)
       (e) Share login credentials or license keys with unauthorized users

   3.2 Number of users, hives, and deployment scope are limited as specified
       in the Order Form.

4. LICENSE TIERS (as specified in Order Form)

   4.1 Enterprise Basic
       - On-premise or cloud deployment
       - Custom deployment assistance
       - Standard support (business hours)
       - Up to specified number of users and hives

   4.2 Enterprise Premium
       - All Enterprise Basic features
       - 24/7 priority support
       - SLA guarantees (99.5% uptime for hosted)
       - Custom integrations and API development
       - Unlimited users and hives

   4.3 White-Label License
       - All Enterprise Premium features
       - Right to rebrand and customize UI
       - Source code access (for modifications)
       - Custom deployment and training

5. SUPPORT AND MAINTENANCE

   5.1 Support level is specified in the Order Form and may include:
       - Email/ticket support
       - Phone support
       - On-site visits
       - Training and onboarding

   5.2 Maintenance includes bug fixes, security patches, and updates as
       released by Licensor.

6. FEES AND PAYMENT

   6.1 Licensee agrees to pay fees as specified in the Order Form.

   6.2 Fees are based on:
       - Number of users
       - Number of hives
       - Deployment type (cloud vs on-premise)
       - Support tier
       - Contract term

   6.3 Payment terms: Net 30 days from invoice date.

   6.4 Late payments incur interest at 1.5% per month or maximum allowed by law.

7. INTELLECTUAL PROPERTY

   7.1 Licensor retains all right, title, and interest in the Software.

   7.2 Licensee owns modifications made to the Software, but grants Licensor
       a perpetual, royalty-free license to incorporate such modifications
       into the Software.

   7.3 Licensee owns all data entered into or generated by the Software.

8. CONFIDENTIALITY

   8.1 Each party agrees to maintain confidentiality of the other party's
       Confidential Information.

   8.2 "Confidential Information" includes source code, business strategies,
       customer lists, and pricing.

9. WARRANTIES

   9.1 Licensor warrants that it has the right to grant this license.

   9.2 THE SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS
       OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
       FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.

   9.3 Licensor does not warrant that the Software will be error-free or
       uninterrupted.

10. LIMITATION OF LIABILITY

    10.1 TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL LICENSOR BE
         LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
         PUNITIVE DAMAGES.

    10.2 LICENSOR'S TOTAL LIABILITY SHALL NOT EXCEED THE FEES PAID BY LICENSEE
         IN THE 12 MONTHS PRECEDING THE CLAIM.

11. TERM AND TERMINATION

    11.1 This Agreement commences on the Effective Date and continues for the
         Term specified in the Order Form.

    11.2 Either party may terminate for material breach if the breach is not
         cured within 30 days of written notice.

    11.3 Upon termination:
         (a) Licensee must cease using the Software
         (b) Licensee may retain data but must delete Software copies
         (c) For perpetual licenses, license survives but support ends
         (d) Fees paid are non-refundable

12. GENERAL PROVISIONS

    12.1 Governing Law: [Your jurisdiction]

    12.2 Entire Agreement: This Agreement and the Order Form constitute the
         entire agreement.

    12.3 Amendments: Must be in writing and signed by both parties.

    12.4 Assignment: Licensee may not assign without Licensor's written consent.

    12.5 Severability: If any provision is invalid, the remainder continues.

13. CONTACT

    For questions about this license, contact:
    Email: pilot@gratheon.com
    Website: https://gratheon.com


ACCEPTANCE

By signing the Order Form or using the Software under this commercial license,
Licensee agrees to be bound by the terms of this Agreement.

_______________________________________________________________________________

Licensor: Gratheon OÜ
Date: _______________
Signature: _______________

_______________________________________________________________________________

Licensee: [Company Name]
Date: _______________
Signature: _______________
Name: _______________
Title: _______________

