name: deploy
on:
  workflow_run:
    workflows: [Unit tests]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    steps:
      - name: pull
        working-directory: /www/web-app/
        run: git reset --hard && git pull

      - name: restart
        working-directory: /www/web-app/
        run: chmod +x restart.sh && ./restart.sh
        
      - name: cleanup
        working-directory: /www/web-app/
        run: rm -rf /www/web-app/node_modules
