name: Build Desktop App

on:
  workflow_run:
    workflows: ["Unit tests"] # Name of the workflow to wait for
    types:
      - completed # Trigger only when the workflow finishes
    branches:
      - master # Only trigger for runs on the master branch

jobs:
  build:
    # Only run this job if the triggering workflow run was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build for ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Match .nvmrc if possible

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          # Use the default stable toolchain for the runner OS
          toolchain: stable

      - name: Install Linux dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential curl wget file libssl-dev libayatana-appindicator3-dev librsvg2-dev

      # macOS dependencies (Xcode CLI) are usually pre-installed on GitHub runners
      # Windows dependencies (MSVC Build Tools, WebView2) are usually pre-installed

      - name: Install frontend dependencies
        run: cd web-app && npm install

      - name: Build Tauri app
        run: npm run tauri build

      - name: Upload Artifact (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: gratheon-linux-${{ github.sha }}
          path: src-tauri/target/release/bundle/appimage/*.AppImage # Correct path relative to root

      - name: Upload Artifact (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: gratheon-macos-${{ github.sha }}
          path: src-tauri/target/release/bundle/macos/*.app # Or .dmg if configured, Correct path relative to root

      - name: Upload Artifact (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: gratheon-windows-${{ github.sha }}
          path: src-tauri/target/release/bundle/msi/*.msi # Correct path relative to root
